<?php


function ubn_entityform_form_alter(&$form, &$form_state, $form_id) {

}


function ubn_entityform_forms($form_id, $args) {
  $forms = array();
  if(strpos($form_id, '_entityform_edit_form') !== FALSE) {
    $forms[$form_id] = array('callback' => 'entityform_edit_form');
  }
  return $forms;
}

function _ubn_entityform_field_collection_field_entityform_type($field_name) {
  $matches = array();
  preg_match('/^field_(\w+?)_form_instance$/', $field_name, $matches);
  return !empty($matches) ? $matches[1] : NULL;
}

function ubn_entityform_field_collection_is_empty_alter(&$is_empty, FieldCollectionItemEntity $item) {
  if (_ubn_entityform_field_collection_field_entityform_type($item->field_name)) {
    $ttx_library = field_get_items('field_collection_item', $item, 'field_ttx_library');
    $ttx_group = field_get_items('field_collection_item', $item, 'field_ttx_group');
    $is_empty = !isset($ttx_library[0]['tid']) || !isset($ttx_group[0]['tid']);
  }
}

function ubn_entityform_form_entityform_edit_form_alter(&$form, &$form_state, $form_id) { 
  $isAnon = $form_state['input']['field_anonymus']['und'];
  if ($isAnon) {
    $form['field_email']['#access'] = FALSE;
    $form['field_full_name']['#access'] = FALSE;
  }

  // need form id to js
  $setting = array(
    'postPath' => $form['#action'],
    'postingStr' => t('Posting'),
    'formId' => '#' . drupal_clean_css_identifier($form_id)
  );

  drupal_add_js(array('ubn_entityform' => array($setting)), 'setting');
  drupal_add_js(drupal_get_path('module', 'ubn_entityform') . '/ubn_entityform.js');
  $entityform = $form['#entity'];
  if (!empty($entityform->ubn_entityform['hidden_fields'])) {
    foreach ($entityform->ubn_entityform['hidden_fields'] as $field_name) {
      $form[$field_name]['#access'] = FALSE;
    }
  }
  /*
  $form['actions']['captcha'] = array(
    '#type' => 'captcha',
    '#captcha_type' => 'recaptcha/reCAPTCHA',
    '#weight' => -99,
  );
  */

  $form['actions']['submit']['#submit'][] = 'ubn_entityform_entityform_edit_form_submit';
  list(, , $bundle) = entity_extract_ids('entityform', $entityform);
  if ($bundle === 'issue') {
    //TODO: Should make sure we are always the last validation handler
    // right now not sure that is always the case (in case other modules add
    // validation handler after us)
    // should implement hook_module_implements_alter?
    $form['#validate'][] = 'ubn_entityform_issue_entityform_edit_form_validate';
  }
  //TODO: add only if submitted!
  $form['#pre_render'][] = '_ubn_entityform_form_status_messages_pre_render';
}

function _ubn_entityform_form_status_messages_pre_render($form) {
  //TODO: only if submitted!
  // Check for general form errors
  $errors = _ubn_entityform_form_get_errors($form['#form_id']);
  $messages_success = _ubn_entityform_form_get_messages_success($form['#form_id']);

  if(!empty($messages_success) || !empty($errors)) {
    $form['ubn_entityform_messages'] = array(
      '#type' => 'container',
      '#attributes' => array('class' => array('ubn-form-status-messages')),
    );
    $container = &$form['ubn_entityform_messages'];
    if(!empty($errors)) {
      $container['errors'] = array(
        '#markup' => slate_render('ubn-entityform-form-errors', array('errors' => $errors)),
      );
    }
    if(!empty($messages_success)) {
      $container['success'] = array(
        '#markup' => slate_render('ubn-entityform-form-messages-success', array('messages' => $messages_success)),
      );
    }
  }
  return $form;
}

function _ubn_entityform_form_set_error($error, $form_id, $type = NULL) {
  form_set_error('ubn_form_' . $form_id . (isset($type) ? '_' . $type : ''), $error);
}

// Break out to separate module?
function _ubn_entityform_form_get_errors($form_id) {
  $errors = form_set_error();
  $ubn_form_errors = array();
  foreach($errors as $name => $error) {
    if(strpos($name, 'ubn_form_' . $form_id) === 0) {
      $ubn_form_errors[$name] = $error;
    }
  }
  return $ubn_form_errors;
}

function _ubn_entityform_form_set_message_success($form_id, $message) {
  _ubn_entityform_form_set_message($form_id, 'success', $message);
}

function _ubn_entityform_form_get_messages_success($form_id) {
  return _ubn_entityform_form_get_messages($form_id, 'success');
}

function _ubn_entityform_form_get_messages($form_id, $type = NULL) {
  if($messages = _ubn_entityform_form_set_message($form_id, $type)) {
    if($type) {
      unset($_SESSION['ubn_entityform_messages'][$form_id][$type]);
      if(empty($_SESSION['ubn_entityform_messages'][$form_id])) {
        unset($_SESSION['ubn_entityform_messages'][$form_id]);
      }
    }
    else {
      unset($_SESSION['ubn_entityform_messages'][$form_id]);
    }
    if(empty($_SESSION['ubn_entityform_messages'])) {
      unset($_SESSION['ubn_entityform_messages']);
    }
    return $messages;
  }
  return array();
}

function _ubn_entityform_form_set_message($form_id, $type = NULL, $message = NULL) {
  if(isset($message)) {
    if(!isset($_SESSION['ubn_entityform_messages'][$form_id][$type])) {
      $_SESSION['ubn_entityform_messages'][$form_id][$type] = array();
    }
    $_SESSION['ubn_entityform_messages'][$form_id][$type][] = $message;
    drupal_page_is_cacheable(FALSE);
  }
  if(isset($type)) {
    return isset($_SESSION['ubn_entityform_messages'][$form_id][$type]) ? $_SESSION['ubn_entityform_messages'][$form_id][$type] : array();
  }
  return isset($_SESSION['ubn_entityform_messages'][$form_id]) ? $_SESSION['ubn_entityform_messages'][$form_id] : array();
}

function ubn_entityform_issue_entityform_edit_form_validate($form, &$form_state) {
  if(form_get_errors()) {
    _ubn_entityform_form_set_error(t('One or more fields has invalid or missing values. Please review errors below.'), $form['#form_id'], 'validation');
  }
  else if ($form_state['submitted'] && !$form_state['rebuild']) {
    //TODO: How does entityform get built? Would be nice to know
    $entityform_wrapper = entity_metadata_wrapper('entityform', $form_state['entityform']);
    global $language_content;
    $ttx_data = array(
      'cmd' => 'newticket',
      //'grp' => $entityform_wrapper->field_ttx_group->field_value->value(),
      'grp' => 'group37',
      'xlibrary' => $entityform_wrapper->field_ttx_library->field_value->value(),
      'lang' => $language_content->language,
      'subject' => $entityform_wrapper->field_title->value(),
      'problem' => $entityform_wrapper->field_message->value(),
      'name' => $entityform_wrapper->field_full_name->value(),
      'email' => $entityform_wrapper->field_email->value(),
      'kid' => time() . '-' . rand(1000000, 9999999),
    );

    $response = drupal_http_request(
      variable_get('ubn_entityform_ttx2easit_endpoint', 'http://130.241.35.161:3006/easitapi/new'),
      array(
        'headers' => array('Content-Type' => 'application/x-www-form-urlencoded'),
        'method' => 'POST',
        'data' => http_build_query($ttx_data, '', '&'),
        'timeout' => 20,
      )
    );

    /*
    $response = new stdClass();
    $response->code = 200;
    */

    if($response->code != 200) {
      _ubn_entityform_form_set_error(t('Sorry! Something went wrong, please try again later.'), $form['#form_id'], 'ttx2easit');
      watchdog(
        'ubn_entityform',
        'Error while submittning @type form (@code: @error).',
        array(
          '@type' => $entityform_wrapper->getBundle(),
          '@code' => $response->code,
          '@error' => $response->error,
        ),
        WATCHDOG_ERROR
      );
    }
    else {
      $message = t('Your message has been received.');
      if(!empty($entityform_wrapper->field_email->value())) {
        $message .= ' ' . t(
          'A confirmation has been sent to %email.',
          array('%email' => $entityform_wrapper->field_email->value())
        );
      }
      _ubn_entityform_form_set_message_success($form['#form_id'], $message);
    }
  }
}

function ubn_entityform_entityform_edit_form_submit(&$form, &$form_state) {
  //TODO: add # to url
  //$form_state['redirect'] = array(current_path(), array('fragement' => 
}

//TODO: array $hidden_fields?
function _ubn_entityform_form_instance_render($field_instance, $entityform_type = NULL) {
  module_load_include('inc', 'entityform', 'entityform.admin');
  global $language_content;

  $issue = entityform_empty_load($entityform_type);
  try {
    $issue_wrapper = entity_metadata_wrapper(
      'entityform',
      $issue,
      array(
        'langcode' => $language_content->language,
      )
    );
  } catch(Exception $e) {
    drupal_set_message($e->getMessage(), 'error');
    watchdog_exception('ubn_entityform', $e);
  }

  $issue->ubn_entityform = array();
  $info_instances = field_info_instances('field_collection_item', $field_instance->field_name->value());
  dsm($info_instances);
  foreach (array_keys($info_instances) as $field_name) {
    // Hide fields storing hidden setting
    if (!preg_match('/_access$/', $field_name)) {
      $issue_wrapper->get($field_name)->set($field_instance->get($field_name)->value());
      if (
        !isset($info_instances[$field_name . '_access']) ||
        !$field_instance->get($field_name . '_access')->value()
      ) {
        dsm($field_name);
        $issue->ubn_entityform['hidden_fields'][] = $field_name;
      }
    }
  }
  //$form = entityform_form_wrapper($issue, 'submit', 'embedded');
  $form = drupal_get_form(
    $issue->type . '_entityform_edit_form_' . $field_instance->getIdentifier(),
    $issue,
    'submit',
    'embedded'
  );
  $form['#attributes']['class'][] = 'entityform';
  $form['#attributes']['class'][] = 'entitytype-' . $issue->type . '-form';
  return drupal_render($form);
}

/**
 * Implements hook_slate_twig_alter().
 *
 * @param $twig
 */
function ubn_entityform_slate_twig_alter(&$twig) {
  $function = new Twig_SimpleFunction(
    'ubn_form_instance_render',
    '_ubn_entityform_form_instance_render'
  );
  $twig->addFunction($function);
}