<?php
/**
 * @file
 */

$plugin = array(
  'title' => t('One column with left sidebar'),
  'theme' => 'onecol_sidebar_left',
  'icon' => '',
  'category' => 'UBNext',
  'regions' => array(
    'header' => t('Header'),
    'main_top' => t('Main top'),
    'alertarea' => t('Alert area'),
    'shortcuts' => t('Shortcuts'),
    'searchbartop' => t('Searchbar (top)'),
    'sidebar' => t('Sidebar'),
    'main' => t('Main'),
  ),
);
