<?php
/**
 * @file
 */


$plugin = array(
  'title' => t('Site template'),
  'theme' => 'site_template',
  'icon' => '',
  'category' => 'UBNext',
  'regions' => array(
    'toplinks' => t('Toplinks'),
    'topbar' => t('Topbar'),
    'navigation' => t('Navigation'),
    'tabs' => t("Tabs"),
    'pagetitle' => t('pagetitle'), /* put title and lead paragraphs here */ 
    'content' => t('Content'),
  ),
);
