<?php
/**
 * @file
 */

$plugin = array(
  'title' => t('Site template'),
  'theme' => 'site_template',
  'icon' => '',
  'category' => 'UBNext',
  'regions' => array(
    'topbar' => t('Top bar'),
    'toplinks' => t('Top links'),
    'navigation' => t('Navigation'),
    'dropdown_navigation' => t('Dropdown navigation used on mobile'),
    'breadcrumb' => t("Breadcrumb"),
    'navigation_secondary' => t('Secondary navigation'),
    'beta' => t('Beta'),
    'tabs' => t("Tabs"),
    'messages' => t('Messages'),
    'pagetitle' => t('Page title'), /* put title and lead paragraphs here */ 
    'content' => t('Content'),
    'footer' => t('Footer'),
  ),
);
