<?php
/**
 * @file
 */

$plugin = array(
  'title' => t('One column full-width'),
  'theme' => 'onecol_full',
  'icon' => '',
  'category' => 'UBNext',
  'regions' => array(
    'messages' => t('Messages'),
    'header' => t('Header'),
    'banner' => t('Banner'),
    'promoted_top' => t('Promoted top'),
    'main_top' => t('Main top'),
    'promoted' => t('Promoted'),
    'main' => t('Main'),
  ),
);
