<?php
/**
 * @file
 * Code for the Search feature.
 */

/*
function ubn_search_menu() {
  $items = array();
  $items['??databases'] = array(
    'title'=> 'Redirecting to database search',
    'type' => MENU_CALLBACK,
    'page callback' => 'ubn_search_database_search_redirect',
    'access callback' => TRUE,
  );
  return $items;
}
*/
function ubn_search_url_inbound_alter(&$path, $original_path, $path_language) {
  if($path === 'databaser') {
    $path = 'databases';
  }
}

function ubn_search_url_outbound_alter(&$path, &$options, $original_path) {
  if($path === 'databases' && $options['language']->language == 'sv') {
    $path = 'databaser';
  }
}

function ubn_search_database_search_redirect() {
  //303 is more correct than 302 since POST/GET should follow the redirect
  drupal_goto('/databases', array(), 303);
}

include_once 'ubn_search.features.inc';
