<?php
/**
 * @file
 * Code for the Dictionary feature.
 */

include_once 'ubn_dictionary.features.inc';


/**
 * Implements hook_ctools_plugin_directory().
 */
function ubn_dictionary_ctools_plugin_directory($owner, $plugin_type) {
  if (in_array($plugin_type, array('content_types'))) {
    return "plugins/$plugin_type";
  }
}

/**
 * Return a list of chars to use as index.
 */
function ubn_dictionary_get_index() {

  return array(
    'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
    'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
    'å', 'ä', 'ö', '0-9',
  );
}

/**
 * Generates html IDs for Terms.
 */
function ubn_dictionary_get_html_id($id) {
  $id = strtr(drupal_strtolower($id), array(
    ' ' => '-',
    '_' => '-',
    '[' => '-',
    ']' => '',
  ));

  $id = preg_replace('/\-+/', '-', $id);

  return $id;
}
