<?php
/**
 * @file
 * Code for the App feature.
 */

include_once 'ubn_app.features.inc';


/**
 * Implements hook_ctools_plugin_directory().
 */
function ubn_app_ctools_plugin_directory($owner, $plugin_type) {
  if (in_array($plugin_type, array('content_types'))) {
    return "plugins/$plugin_type";
  }
}


/**
 * Helper function to include an app.
 */
function ubn_app_include_app(EntityDrupalWrapper $app) {
  global $language;

  $name = $app->field_app_name->value();
  $base_url = rtrim($app->field_app_base_url->value());

  drupal_add_js("{$base_url}/vendor.js", 'external');
  drupal_add_js("{$base_url}/{$name}.js", 'external');

  drupal_add_css("{$base_url}/vendor.css", array('type' => 'external'));
  drupal_add_css("{$base_url}/{$name}.css", array('type' => 'external'));


  $attributes = array(
    'id' => "ember-app-{$name}",
    'data-lang' => $language->language,
  );

  foreach ($app->field_app_properties as $property) {
    $name = $property->field_app_properties_name->value();
    $value = $property->field_app_properties_value->value();

    $attributes["data-{$name}"] = $value;
  }

  return '<div' . drupal_attributes($attributes) . '"></div>';
}
