<?php
/**
 * @file
 * Code for the UBN Library feature.
 */

include_once 'ubn_library.features.inc';
/*
// Probably not needed anymore since fixed in feeds processor
function ubn_library_entity_presave($entity, $type) {
  if($type === 'field_collection_item' && $entity->field_name === 'field_opening_hours') {
    $handler = entity_translation_get_handler($type, $entity);
    $handler->setFormLanguage($handler->getDefaultLanguage());
  }
}
*/

function ubn_library_form_node_form_alter(&$form, $form_state, $form_id) {
  if ($form_id === 'library_node_form') {
    $form['menu']['#access'] = FALSE;
  }
}
