<?php
/**
 * @file
 */

$plugin = array(
  'title' => t('Frontpage'),
  'theme' => 'front',
  'icon' => '',
  'category' => 'UBNext',
  'regions' => array(
    'search' => t('Search'),
    'messages' => t('Messages'),
    'services' => t('Services'),
    'navigation' => t('Navigation'),
    'promoted_top' => t('Promoted top'),
    'news' => t('News'),
    'promoted' => t('Promoted'),
    'main' => t('Main'),
  ),
);
