<?php

/**
 * 
 */
function ubn_footer_form_system_site_information_settings_alter(&$form, &$form_state, $form_id) {
   $form['footer_fieldset'] = array(
        '#type' => 'fieldset',
        '#title' => t('FOOTER'),
        '#collapsible' => TRUE,
//        '#tree' => TRUE,
    );
   	$default_value = variable_get('footer_col1', array('value' => NULL, 'format' => NULL));
    $form['footer_fieldset']['footer_col1'] = array(
      '#type' => 'text_format',
      '#title' => t('Column 1'),
       '#default_value' => $default_value['value'],
       '#format' => $default_value['format'],
    );
    $default_value = variable_get('footer_col2', array('value' => NULL, 'format' => NULL));
    $form['footer_fieldset']['footer_col2'] = array(
      '#type' => 'text_format',
      '#title' => t('Column 2'),
       '#default_value' => $default_value['value'],
       '#format' => $default_value['format'],
    );
    $default_value = variable_get('footer_col3', array('value' => NULL, 'format' => NULL));
    $form['footer_fieldset']['footer_col3'] = array(
      '#type' => 'text_format',
      '#title' => t('Column 3'),
       '#default_value' => $default_value['value'],
       '#format' => $default_value['format'],
    );

    //$form['#submit'][] = '_ubn_footer_form_submit';
}


