<?php

/**
 * 
 */
function ubn_footer_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'system_site_information_settings') {
   $form['footer_fieldset'] = array(
        '#type' => 'fieldset',
        '#title' => t('FOOTER'),
        '#collapsible' => TRUE,
//        '#tree' => TRUE,
    );
    $form['footer_fieldset']['col1'] = array(
      '#type' => 'text_format',
      '#title' => t('Column 1'),
       '#default_value' => variable_get('col1')['value'],
    );
    $form['footer_fieldset']['col2'] = array(
      '#type' => 'text_format',
      '#title' => t('Column 2'),
       '#default_value' => variable_get('col2')['value'],
    );
    $form['footer_fieldset']['col3'] = array(
      '#type' => 'text_format',
      '#title' => t('Column 3'),
       '#default_value' => variable_get('col3')['value'],
    );
  }
// extra submit form handle
  $form['#submit'][] = '_ubn_footer_form_submit';
}


function _ubn_footer_form_submit($form, &$form_state) {
	$values = $form_state['values'];
    if(!empty($values['col1'])){
        variable_set('col1', $values['col1']);
    }
    if(!empty($values['col2'])){
        variable_set('col2', $values['col2']);
    }
    if(!empty($values['col3'])){
        variable_set('col3', $values['col3']);
    }
}
