<?php
/**
 * @file
 * Code for the UBN News feature.
 */

include_once 'ubn_news.features.inc';

function ubn_news_url_inbound_alter(&$path, $original_path, $path_language) {
  if($path === 'nyheter') {
    $path = 'news';
  }
}

function ubn_news_url_outbound_alter(&$path, &$options, $original_path) {
  if($path === 'news' && $options['language']->language == 'sv') {
    $path = 'nyheter';
  }
}



/**
 * Implements hook_page_delivery_callback_alter().
 *
 * This is the only hook that occurs after the page callback, but before
 * hook_page_build (when blocks are added). We're using this hook for its
 * timing, not its data.
 */
/*
function ubn_news_page_delivery_callback_alter() {
  // refactor set active trail
  // Build a small context.
  $context = array(
    'path' => $_GET['q'],
    'entity_type' => NULL,
    'bundle_name' => NULL,
  );
  // Determine what kind of entity page this is.
  list($arg0, $arg1, $arg2) = explode('/', $context['path'] . '//');
  if ($arg0 == 'node' && is_numeric($arg1)) {
    $context['node'] = node_load($arg1);
    // Don't evaluate the rules on a 404 page.
    if (!$context['node']) {
      return;
    }
    $context['entity_type'] = 'node';
    $context['bundle_name'] = $context['node']->type;
    if ($context['bundle_name'] == 'story') {
      // rewrite breadcrumb
      $breadcrumb = array();
      $breadcrumb[] = l('Home', '<front>');
      $breadcrumb[] = l(t('News'), 'news');
      $breadcrumb[] = drupal_get_title();
      //drupal_set_breadcrumb($breadcrumb);
    }
  }
}
*/

// Might be a better hook for this, but since we will probably replace
// view with ctools content type this is good enough for now
function ubn_news_views_pre_render($view) {
  if ($view->current_display === 'latest_stories_promoted') {
    drupal_add_js(drupal_get_path('module', 'ubn_news') . '/ubn_news.js');
  }
}
