<?php
/**
 * Implements hook_ctools_plugin_directory().
 */
function ubn_menu_ctools_plugin_directory($owner, $plugin_type) {
  if (in_array($plugin_type, array('content_types'))) {
    return "plugins/$plugin_type";
  }
}


function ubn_menu_menu_link_alter(&$item) {
  // Flag a link to be altered by hook_translated_menu_link_alter().
  if ($item['link_title'] == 'News') {
    $item['options']['alter'] = TRUE;
  }
}

function ubn_menu_translated_menu_link_alter(&$item, $map) {
  if ($item['menu_name'] == 'main-menu') {
    if ($item['link_title'] == 'News') {
      //$item['hidden'] = 1;
      $item['ubn_menu_hidden'] = TRUE;
    }
  }

}
