<?php
/**
 * Implements hook_ctools_plugin_directory().
 */
function ubn_menu_ctools_plugin_directory($owner, $plugin_type) {
  if (in_array($plugin_type, array('content_types'))) {
    return "plugins/$plugin_type";
  }
}

/**
  * Implements hook_menu_alter().
 */
function ubn_menu_menu_alter(&$items) {
  foreach(array('databases/search', 'news') as $default_menu_item_to_callback_path) {
    if (isset($items[$default_menu_item_to_callback_path])) {
      // This does not seems to work all the time, no idea why
      $items[$default_menu_item_to_callback_path]['type'] = MENU_CALLBACK;
    }
    else {
      drupal_set_message(
        "Missing \"$default_menu_item_to_callback_path\" router path, fix this in ubn_menu.module.",
        'error'
      );
    }
  }
  // hides registration link on login page
  unset($items['user/register']);
}

function ubn_menu_query_preferred_menu_links_alter(QueryAlterableInterface $query) {
  $and = db_and();
  $query->condition(db_or()
    ->condition('ml.menu_name', 'navigation', '<>')
    ->condition(db_and()
      ->condition('ml.link_title', 'Stories', '<>')
      ->condition('ml.link_title', 'Databases', '<>')
    )
  );
}

function ubn_menu_menu_link_alter(&$item) {
  // Flag a link to be altered by hook_translated_menu_link_alter().
  foreach (array('News', 'Databases', 'A-Z') as $title) {
    if ($item['link_title'] === $title) {
      $item['options']['alter'] = TRUE;
      break;
    }
  }
}

function ubn_menu_translated_menu_link_alter(&$item, $map) {
  if ($item['menu_name'] == 'main-menu') {
    foreach (array('News', 'Databases', 'A-Z') as $title) {
      if ($item['link_title'] === $title) {
        //$item['hidden'] = 1;
        $item['ubn_menu_hidden'] = TRUE;
        break;
      }
    }
  }
}
