<?php
function ubn_markdown_filter_info() {
  return array(
    'ubn_markdown' => array(
      'title' => t('UBN Markdown extras'),
      'description' => t("Markdown extension for UBNext"),
      'process callback' => '_ubn_markdown',
      //'settings callback' => '_ubn_markdown_settings',
      //'default settings' => array(),
      'tips callback' => '_ubn_markdown_tips',
    ),
  );
}
// TODO: use slate instead? 
function _ubn_markdown_replace_callback($matches) {
  return slate_render('ubn-markdown-call-to-action', array(
    'title' => isset($matches['title']) ? $matches['title'] : '',
    'content' => $matches['content'],
    'link_href' => isset($matches['link_href']) ? $matches['link_href'] : '',
    'link_text' => isset($matches['link_text']) ? $matches['link_text'] : '',
    'link_title' => isset($matches['link_title']) ? $matches['link_title'] : '',
  ));
}

function _ubn_markdown($text, $format) {
  // Simplified parsing of links compared to php-markdown
  // but probably good enough
  return preg_replace_callback('/
    ^\!{3,}\h*$           # Begin call to action block (!!!)
    \s*
    (?:^\#+\h*(?P<title>[^\r\n]+))?
    (?P<content>.+?)
    \s*
    (?:
      ^\[
        (?P<link_text>.+?)
      \]
      \(
        (?P<link_href>.+?)
        (?:\s*[\"\'](?P<link_title>.+?)[\"\'])? #TODO: backreference group matching thing instead of \"\'
      \)
    )?
    \s*
    ^\!{3,}\h*$           # End call to action block (!!!)
    /msx', '_ubn_markdown_replace_callback', $text);
}

function _ubn_markdown_tips($filter, $format, $long = FALSE) {
  return $long ?
    'Long description todo' :
    'Short description todo';
}
