<?php
/**
 * @file
 * Code for the Ubn Startpage feature.
 */

include_once 'ubn_startpage.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function ubn_startpage_ctools_plugin_directory($owner, $plugin_type) {
  if (in_array($plugin_type, array('content_types'))) {
    return "plugins/$plugin_type";
  }
}



function ubn_startpage_entity_update($entity, $type) {
  if ($type === 'entityqueue_subqueue') {
    cache_clear_all();
  }
}

//Must be run before slate entity_info_alter?
function ubn_startpage_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['ubn_blurb_primary'] = array(
    'label' => t('UBN Blurb primary'),
    'custom settings' => FALSE,
  );
  $entity_info['node']['view modes']['ubn_blurb_navigation'] = array(
    'label' => t('UBN Blurb navigation'),
    'custom settings' => FALSE,
  );
  $entity_info['node']['view modes']['ubn_blurb'] = array(
    'label' => t('UBN Blurb'),
    'custom settings' => FALSE,
  );
}

