<?php
/**
 * @file
 * ubn_contact_content.features.uuid_entity_taxonomy_term.inc
 */

/**
 * Implements hook_uuid_entity_default_taxonomy_term().
 */
function ubn_contact_content_uuid_entity_default_taxonomy_term() {
  $items = array();
  $items['0c3eda10-a4e2-4842-a607-ed9d33ab7185'] = entity_create('taxonomy_term', array(
    'name' => 'Summon',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => '0c3eda10-a4e2-4842-a607-ed9d33ab7185',
    'vocabulary_machine_name' => 'ttx_group',
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'group33',
          'format' => NULL,
          'safe_value' => 'group33',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'language' => 'und',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['13e497a2-e53e-4d32-a97b-2131881bb59e'] = entity_create('taxonomy_term', array(
    'name' => 'Kursböcker',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => '13e497a2-e53e-4d32-a97b-2131881bb59e',
    'vocabulary_machine_name' => 'ttx_group',
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'group27',
          'format' => NULL,
          'safe_value' => 'group27',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'language' => 'und',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['1d20862f-f44b-46a0-8727-a3b97f9606eb'] = entity_create('taxonomy_term', array(
    'name' => 'Läs- och skrivstöd',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => '1d20862f-f44b-46a0-8727-a3b97f9606eb',
    'vocabulary_machine_name' => 'ttx_group',
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'group24',
          'format' => NULL,
          'safe_value' => 'group24',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'language' => 'und',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['20c74674-ae25-449b-becc-9d585f4c966e'] = entity_create('taxonomy_term', array(
    'name' => 'Biomedical Library - Learning Centre',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => '20c74674-ae25-449b-becc-9d585f4c966e',
    'vocabulary_machine_name' => 'ttx_library',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Biomedical Library - Learning Centre',
          'format' => NULL,
          'safe_value' => 'Biomedical Library - Learning Centre',
        ),
      ),
      'sv' => array(
        0 => array(
          'value' => 'Studietorget Hälsovetarbacken',
          'format' => NULL,
          'safe_value' => 'Studietorget Hälsovetarbacken',
        ),
      ),
    ),
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'Biomedical Library - Learning Centre',
          'format' => NULL,
          'safe_value' => 'Biomedical Library - Learning Centre',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'sv',
      'data' => array(
        'sv' => array(
          'language' => 'sv',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
        'en' => array(
          'language' => 'en',
          'source' => 'sv',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['24100d4d-71aa-4276-9c5b-7b423a6f1254'] = entity_create('taxonomy_term', array(
    'name' => 'Test',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => '24100d4d-71aa-4276-9c5b-7b423a6f1254',
    'vocabulary_machine_name' => 'ttx_group',
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'group37',
          'format' => NULL,
          'safe_value' => 'group37',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'language' => 'und',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['2b5e9e90-8fd0-4b60-9984-bd526fe70de8'] = entity_create('taxonomy_term', array(
    'name' => 'Kontakta överbibliotekarien',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => '2b5e9e90-8fd0-4b60-9984-bd526fe70de8',
    'vocabulary_machine_name' => 'ttx_group',
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'group7',
          'format' => NULL,
          'safe_value' => 'group7',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'language' => 'und',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['2d1a9656-e0be-472f-9fc6-e385727e5688'] = entity_create('taxonomy_term', array(
    'name' => 'Undervisning',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => '2d1a9656-e0be-472f-9fc6-e385727e5688',
    'vocabulary_machine_name' => 'ttx_group',
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'group14',
          'format' => NULL,
          'safe_value' => 'group14',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'language' => 'und',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['2e018002-c2c7-4d3b-85a4-1535b2d7d72b'] = entity_create('taxonomy_term', array(
    'name' => 'Bibliometri',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => '2e018002-c2c7-4d3b-85a4-1535b2d7d72b',
    'vocabulary_machine_name' => 'ttx_group',
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'group21',
          'format' => NULL,
          'safe_value' => 'group21',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'language' => 'und',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['30fe9ef3-6d14-48bd-ab41-0cc2dab33ab1'] = entity_create('taxonomy_term', array(
    'name' => 'Räkningsärenden',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => '30fe9ef3-6d14-48bd-ab41-0cc2dab33ab1',
    'vocabulary_machine_name' => 'ttx_group',
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'group18',
          'format' => NULL,
          'safe_value' => 'group18',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'language' => 'und',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['340a8f0c-f545-4d63-93e8-298369a72b1b'] = entity_create('taxonomy_term', array(
    'name' => 'Digit-utvecklarna',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => '340a8f0c-f545-4d63-93e8-298369a72b1b',
    'vocabulary_machine_name' => 'ttx_group',
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'group36',
          'format' => NULL,
          'safe_value' => 'group36',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'language' => 'und',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['37aed788-abd3-47cc-909c-5a0937665122'] = entity_create('taxonomy_term', array(
    'name' => 'Digitalisering',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => '37aed788-abd3-47cc-909c-5a0937665122',
    'vocabulary_machine_name' => 'ttx_group',
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'group38',
          'format' => NULL,
          'safe_value' => 'group38',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'language' => 'und',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['3a42a731-5190-4e43-be66-145332a69023'] = entity_create('taxonomy_term', array(
    'name' => 'GUNDA',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => '3a42a731-5190-4e43-be66-145332a69023',
    'vocabulary_machine_name' => 'ttx_group',
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'group1',
          'format' => NULL,
          'safe_value' => 'group1',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'language' => 'und',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['44794526-92e9-4ce7-88aa-018dd0f22074'] = entity_create('taxonomy_term', array(
    'name' => 'Music and Drama Library',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => '44794526-92e9-4ce7-88aa-018dd0f22074',
    'vocabulary_machine_name' => 'ttx_library',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Music and Drama Library',
          'format' => NULL,
          'safe_value' => 'Music and Drama Library',
        ),
      ),
      'sv' => array(
        0 => array(
          'value' => 'Biblioteket för musik och dramatik',
          'format' => NULL,
          'safe_value' => 'Biblioteket för musik och dramatik',
        ),
      ),
    ),
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'Music and Drama Library',
          'format' => NULL,
          'safe_value' => 'Music and Drama Library',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'sv',
      'data' => array(
        'sv' => array(
          'language' => 'sv',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
        'en' => array(
          'language' => 'en',
          'source' => 'sv',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['5a15e618-81c2-42e0-8fe6-75a8a94e5bfc'] = entity_create('taxonomy_term', array(
    'name' => 'Biomedical Library',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => '5a15e618-81c2-42e0-8fe6-75a8a94e5bfc',
    'vocabulary_machine_name' => 'ttx_library',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Biomedical Library',
          'format' => NULL,
          'safe_value' => 'Biomedical Library',
        ),
      ),
      'sv' => array(
        0 => array(
          'value' => 'Biomedicinska biblioteket',
          'format' => NULL,
          'safe_value' => 'Biomedicinska biblioteket',
        ),
      ),
    ),
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'Biomedical Library',
          'format' => NULL,
          'safe_value' => 'Biomedical Library',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'sv',
      'data' => array(
        'sv' => array(
          'language' => 'sv',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
        'en' => array(
          'language' => 'en',
          'source' => 'sv',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['67f0c8da-8015-41ee-be9c-85de635e3d8c'] = entity_create('taxonomy_term', array(
    'name' => 'ACTA',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => '67f0c8da-8015-41ee-be9c-85de635e3d8c',
    'vocabulary_machine_name' => 'ttx_group',
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'group13',
          'format' => NULL,
          'safe_value' => 'group13',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'language' => 'und',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['6ae4adba-6e07-4559-b0fb-a6a39ee027d5'] = entity_create('taxonomy_term', array(
    'name' => 'Webbteam',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => '6ae4adba-6e07-4559-b0fb-a6a39ee027d5',
    'vocabulary_machine_name' => 'ttx_group',
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'group8',
          'format' => NULL,
          'safe_value' => 'group8',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'language' => 'und',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['6e8a5141-7679-4d3e-9e6c-89c7344e666e'] = entity_create('taxonomy_term', array(
    'name' => 'Konstbiblioteket',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => '6e8a5141-7679-4d3e-9e6c-89c7344e666e',
    'vocabulary_machine_name' => 'ttx_library',
    'name_field' => array(
      'sv' => array(
        0 => array(
          'value' => 'Konstbiblioteket',
          'format' => NULL,
          'safe_value' => 'Konstbiblioteket',
        ),
      ),
    ),
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'Art Library',
          'format' => NULL,
          'safe_value' => 'Art Library',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'sv',
      'data' => array(
        'sv' => array(
          'language' => 'sv',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['70d93717-6e43-4445-9eab-222c27ae983d'] = entity_create('taxonomy_term', array(
    'name' => 'Humanities Library',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => '70d93717-6e43-4445-9eab-222c27ae983d',
    'vocabulary_machine_name' => 'ttx_library',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Humanities Library',
          'format' => NULL,
          'safe_value' => 'Humanities Library',
        ),
      ),
      'sv' => array(
        0 => array(
          'value' => 'Humanistiska biblioteket',
          'format' => NULL,
          'safe_value' => 'Humanistiska biblioteket',
        ),
      ),
    ),
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'Humanities Library',
          'format' => NULL,
          'safe_value' => 'Humanities Library',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'sv',
      'data' => array(
        'sv' => array(
          'language' => 'sv',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
        'en' => array(
          'language' => 'en',
          'source' => 'sv',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['73627958-1a38-4c76-93a2-213e6d7647f5'] = entity_create('taxonomy_term', array(
    'name' => 'Handskrifter',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => '73627958-1a38-4c76-93a2-213e6d7647f5',
    'vocabulary_machine_name' => 'ttx_group',
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'group16',
          'format' => NULL,
          'safe_value' => 'group16',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'language' => 'und',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['7650c0bf-66bb-420d-acaa-a52c054169eb'] = entity_create('taxonomy_term', array(
    'name' => 'Miljö/Lokal',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => '7650c0bf-66bb-420d-acaa-a52c054169eb',
    'vocabulary_machine_name' => 'ttx_group',
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'group2',
          'format' => NULL,
          'safe_value' => 'group2',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'language' => 'und',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['7986493e-8c98-4fe3-8b19-f4f6816211aa'] = entity_create('taxonomy_term', array(
    'name' => 'Forskarservice',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => '7986493e-8c98-4fe3-8b19-f4f6816211aa',
    'vocabulary_machine_name' => 'ttx_group',
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'group34',
          'format' => NULL,
          'safe_value' => 'group34',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'language' => 'und',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['8879d243-b1a9-404e-9a19-24d606e0063b'] = entity_create('taxonomy_term', array(
    'name' => 'Social Sciences Library',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => '8879d243-b1a9-404e-9a19-24d606e0063b',
    'vocabulary_machine_name' => 'ttx_library',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Social Sciences Library',
          'format' => NULL,
          'safe_value' => 'Social Sciences Library',
        ),
      ),
      'sv' => array(
        0 => array(
          'value' => 'Samhällsvetenskapliga biblioteket',
          'format' => NULL,
          'safe_value' => 'Samhällsvetenskapliga biblioteket',
        ),
      ),
    ),
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'Social Sciences Library',
          'format' => NULL,
          'safe_value' => 'Social Sciences Library',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'sv',
      'data' => array(
        'sv' => array(
          'language' => 'sv',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
        'en' => array(
          'language' => 'en',
          'source' => 'sv',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['9281b091-3083-4af4-90b3-de006a0b887b'] = entity_create('taxonomy_term', array(
    'name' => 'Campus Linne',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => '9281b091-3083-4af4-90b3-de006a0b887b',
    'vocabulary_machine_name' => 'ttx_library',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Campus Linne',
          'format' => NULL,
          'safe_value' => 'Campus Linne',
        ),
      ),
      'sv' => array(
        0 => array(
          'value' => 'Studietorget Campus Linne',
          'format' => NULL,
          'safe_value' => 'Studietorget Campus Linne',
        ),
      ),
    ),
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'Campus Linne',
          'format' => NULL,
          'safe_value' => 'Campus Linne',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'sv',
      'data' => array(
        'sv' => array(
          'language' => 'sv',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
        'en' => array(
          'language' => 'en',
          'source' => 'sv',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['96357307-b509-42ab-a385-af2f783dc588'] = entity_create('taxonomy_term', array(
    'name' => 'Katalogisering',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => '96357307-b509-42ab-a385-af2f783dc588',
    'vocabulary_machine_name' => 'ttx_group',
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'group35',
          'format' => NULL,
          'safe_value' => 'group35',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'language' => 'und',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['9a3402f6-f516-4ddf-9b01-9bdbdaa0b853'] = entity_create('taxonomy_term', array(
    'name' => 'Pedagogiska biblioteket',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => '9a3402f6-f516-4ddf-9b01-9bdbdaa0b853',
    'vocabulary_machine_name' => 'ttx_library',
    'name_field' => array(
      'sv' => array(
        0 => array(
          'value' => 'Pedagogiska biblioteket',
          'format' => NULL,
          'safe_value' => 'Pedagogiska biblioteket',
        ),
      ),
    ),
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'Education Library',
          'format' => NULL,
          'safe_value' => 'Education Library',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'sv',
      'data' => array(
        'sv' => array(
          'language' => 'sv',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['ad1328b6-a7ec-4ec2-bc14-521593cc3356'] = entity_create('taxonomy_term', array(
    'name' => 'Tyck till',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => 'ad1328b6-a7ec-4ec2-bc14-521593cc3356',
    'vocabulary_machine_name' => 'ttx_group',
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'group10',
          'format' => NULL,
          'safe_value' => 'group10',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'language' => 'und',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['b597196d-0d08-4a43-8f93-1e813f093002'] = entity_create('taxonomy_term', array(
    'name' => 'Tidskrifter',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => 'b597196d-0d08-4a43-8f93-1e813f093002',
    'vocabulary_machine_name' => 'ttx_group',
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'group6',
          'format' => NULL,
          'safe_value' => 'group6',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'language' => 'und',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['cb9eb0b7-e35f-4398-8323-0f5807fe1a4e'] = entity_create('taxonomy_term', array(
    'name' => 'Biblioteksdisk',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => 'cb9eb0b7-e35f-4398-8323-0f5807fe1a4e',
    'vocabulary_machine_name' => 'ttx_group',
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'group4',
          'format' => NULL,
          'safe_value' => 'group4',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'language' => 'und',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['d1901348-50c5-4e50-a831-5c56ac88bfe3'] = entity_create('taxonomy_term', array(
    'name' => 'Publicering, GUP/GUPEA',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => 'd1901348-50c5-4e50-a831-5c56ac88bfe3',
    'vocabulary_machine_name' => 'ttx_group',
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'group3',
          'format' => NULL,
          'safe_value' => 'group3',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'language' => 'und',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['d68dceb5-2f44-4873-bf5c-c653559be7c1'] = entity_create('taxonomy_term', array(
    'name' => 'KvinnSam',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => 'd68dceb5-2f44-4873-bf5c-c653559be7c1',
    'vocabulary_machine_name' => 'ttx_group',
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'group17',
          'format' => NULL,
          'safe_value' => 'group17',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'language' => 'und',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['df817bd3-226d-4048-b162-e56dc14d6e13'] = entity_create('taxonomy_term', array(
    'name' => 'Fjärrlån',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => 'df817bd3-226d-4048-b162-e56dc14d6e13',
    'vocabulary_machine_name' => 'ttx_group',
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'group20',
          'format' => NULL,
          'safe_value' => 'group20',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'language' => 'und',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['e190cac4-4f74-4a20-9e8e-189b5ebdb468'] = entity_create('taxonomy_term', array(
    'name' => 'E-support',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => 'e190cac4-4f74-4a20-9e8e-189b5ebdb468',
    'vocabulary_machine_name' => 'ttx_group',
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'group25',
          'format' => NULL,
          'safe_value' => 'group25',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'language' => 'und',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['e317540a-901f-4f49-8a74-7de5fcc53015'] = entity_create('taxonomy_term', array(
    'name' => 'Earth Sciences Library',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => 'e317540a-901f-4f49-8a74-7de5fcc53015',
    'vocabulary_machine_name' => 'ttx_library',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Earth Sciences Library',
          'format' => NULL,
          'safe_value' => 'Earth Sciences Library',
        ),
      ),
      'sv' => array(
        0 => array(
          'value' => 'Geovetenskapliga biblioteket',
          'format' => NULL,
          'safe_value' => 'Geovetenskapliga biblioteket',
        ),
      ),
    ),
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'Earth Sciences Library',
          'format' => NULL,
          'safe_value' => 'Earth Sciences Library',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'sv',
      'data' => array(
        'sv' => array(
          'language' => 'sv',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
        'en' => array(
          'language' => 'en',
          'source' => 'sv',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['eef4521a-55c7-4a3d-b4c2-d2721aa94afa'] = entity_create('taxonomy_term', array(
    'name' => 'Economics Library',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => 'eef4521a-55c7-4a3d-b4c2-d2721aa94afa',
    'vocabulary_machine_name' => 'ttx_library',
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Economics Library',
          'format' => NULL,
          'safe_value' => 'Economics Library',
        ),
      ),
      'sv' => array(
        0 => array(
          'value' => 'Ekonomiska biblioteket',
          'format' => NULL,
          'safe_value' => 'Ekonomiska biblioteket',
        ),
      ),
    ),
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'Economics Library',
          'format' => NULL,
          'safe_value' => 'Economics Library',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'sv',
      'data' => array(
        'sv' => array(
          'language' => 'sv',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
        'en' => array(
          'language' => 'en',
          'source' => 'sv',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['f06f2e90-13bf-4f32-aeea-9b64f6fd948c'] = entity_create('taxonomy_term', array(
    'name' => 'Förvärv',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => 'f06f2e90-13bf-4f32-aeea-9b64f6fd948c',
    'vocabulary_machine_name' => 'ttx_group',
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'group15',
          'format' => NULL,
          'safe_value' => 'group15',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'language' => 'und',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  $items['fc19497c-1e9b-4e5e-817e-638b2c0ddc03'] = entity_create('taxonomy_term', array(
    'name' => 'E-böcker',
    'description' => '',
    'format' => 'markdown',
    'weight' => 0,
    'uuid' => 'fc19497c-1e9b-4e5e-817e-638b2c0ddc03',
    'vocabulary_machine_name' => 'ttx_group',
    'field_value' => array(
      'und' => array(
        0 => array(
          'value' => 'group11',
          'format' => NULL,
          'safe_value' => 'group11',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'und',
      'data' => array(
        'und' => array(
          'language' => 'und',
          'source' => '',
          'status' => 1,
          'translate' => 0,
        ),
      ),
    ),
    'path' => array(
      'pathauto' => 1,
    ),
  ));
  return $items;
}
