<?php
/**
 * @file
 * Code for the Guide feature.
 */

include_once 'ubn_guide.features.inc';


/**
 * Implements hook_ctools_plugin_directory().
 */
function ubn_guide_ctools_plugin_directory($owner, $plugin_type) {
  if (in_array($plugin_type, array('content_types'))) {
    return "plugins/$plugin_type";
  }
}

/**
 * Implements hook_path_update().
 */
function ubn_guide_path_update($path) {
  $node = menu_get_object('node', 1, $path['source']);

  if (!isset($node->type) || !in_array($node->type, array('guide', 'guide_chapter'))) {
    return;
  }

  $children = array_keys(ubn_guide_get_children($node->nid, 1));

  if (empty($children)) {
    return;
  }

  // Clear path cache for source edit page, and do it only once.
  if (($clear = &drupal_static(__FUNCTION__, TRUE)) === TRUE) {
    cache_clear_all("{$path['source']}/edit", 'cache_path');

    $clear = FALSE;
  }

  pathauto_node_update_alias_multiple($children, 'bulkupdate');
}

/**
 * Get root node
 *
 * @todo use ubn_guide_get_parents()
 */
function ubn_guide_get_root(EntityDrupalWrapper $node) {
  switch ($node->getBundle()) {
    case 'guide':
      return $node;

    case 'guide_chapter':
      return ubn_guide_get_root($node->field_guide_chapter_parent);

    default:
      throw new Exception('Invalid bundle.');
  }
}

/**
 * Get children as a tree.
 *
 * @todo cache?
 */
function ubn_guide_get_children($nid, $depth = -1) {
  $children = array();

  if ($depth === 0) {
    return $children;
  }

  $query = new EntityFieldQuery();

  $query
    ->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'guide_chapter')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->fieldCondition('field_guide_chapter_parent', 'target_id', $nid)
    ->fieldOrderBy('field_guide_chapter_weight', 'value', 'ASC');

  $result = $query->execute();

  if (!empty($result['node'])) {
    foreach ($result['node'] as $child) {
      $children[$child->nid] = ubn_guide_get_children($child->nid, $depth - 1);
    }
  }

  return $children;
}

/**
 * Return a list of parents.
 */
function ubn_guide_get_parents(EntityDrupalWrapper $node) {
  switch ($node->getBundle()) {
    case 'guide':
      return array();

    case 'guide_chapter':
      return array_merge(array($node->field_guide_chapter_parent->getIdentifier()), ubn_guide_get_parents($node->field_guide_chapter_parent));

    default:
      throw new Exception('Invalid bundle.');
  }
}

/**
 * Flatten a tree of children.
 */
function ubn_guide_flatten($tree) {
  $flat = array();

  foreach ($tree as $id => $children) {
    $flat[] = $id;

    if (!empty($children)) {
      $flat = array_merge($flat, ubn_guide_flatten($children));
    }
  }

  return $flat;
}

/**
 * Finds the prev chapter for a guide/chapter.
 */
function ubn_guide_find_prev_chapter(EntityDrupalWrapper $node) {
  $root = ubn_guide_get_root($node);

  if ($root === $node) {
    return FALSE;
  }

  $children = ubn_guide_get_children($root->getIdentifier());
  $flatten = ubn_guide_flatten($children);

  $index = array_search($node->getIdentifier(), $flatten);

  if ($index === 0) {
    return $root->getIdentifier();
  }

  return $flatten[$index - 1];
}

/**
 * Finds the next chapter for a guide/chapter.
 */
function ubn_guide_find_next_chapter(EntityDrupalWrapper $node) {
  $root = ubn_guide_get_root($node);

  $children = ubn_guide_get_children($root->getIdentifier());

  if (empty($children)) {
    return FALSE;
  }

  $flatten = ubn_guide_flatten($children);

  if ($root === $node) {
    return $flatten[0];
  }

  $index = array_search($node->getIdentifier(), $flatten);

  return isset($flatten[$index + 1]) ? $flatten[$index + 1] : FALSE;
}
